### ISSUE TITLE
`org.brotli:dec:0.1.2` appears as `${project.groupId}:${project.artifactId}`

### ISSUE THREAD

**Issue by bric3** [cloudflightio/license-gradle-plugin#12]
Hi, thank you for the plugin, it works quite well.

I noticed a few things that are related to maven poms, eg with the following dependency `org.brotli:dec:0.1.2` the resulting name is this string `${project.groupId}:${project.artifactId} (0.1.2)`:

![image](https://user-images.githubusercontent.com/803621/196737750-f133186f-29a2-4176-879b-8b4f07f8a6ff.png)

The pom us indeed `<name>${project.groupId}:${project.artifactId}</name>`, I don't think gradle can understand that, but maybe there's a way to perform simple substitutions, like for `groupId` and `artifactId` ?

**Comment by bric3** [comment]
Thanks for the fix!

**Comment by klu2** [comment]
thanks for reporting, it's released under https://github.com/cloudflightio/license-gradle-plugin/releases/tag/1.2.0
